name: be_loved
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cupertino_rounded_corners: ^2.1.1
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1
  pinput: ^2.2.12
  smooth_page_indicator: ^1.0.0+2
  flutter_native_splash: ^2.2.9
  scroll_date_picker: ^3.6.0
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  dio: ^4.0.6

  image_picker: ^0.8.5+3
  flutter_image_compress: ^1.1.3

  #BloC
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  overlay_support: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/icons/

  uses-material-design: true

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
